### ISSUE TITLE
Create cumulative carbon emissions for episode.

### ISSUE THREAD

**Issue by cameron-raymond** [ZaneLittle/Traffic-Light-Simulation#13]
Probably just take the wait time list returned in the simulation and convert it to be a cumulative sum, multiplied by how much carbon emission a car releases in a timeframe?

[4, 6, 12] -> [4, 4+6, 4+6+12]*c -> [4, 10, 20]*c

**Comment by ZaneLittle** [comment]
The wait time list, added in a4700fbae0f74705db2410a90e4617256bf03f42, is implemented as a daily average travel time of all cars. This can basically be multiplied by a scalar which would be the ratio between our "time traveled" and carbon emissions per time tick.

Some data from https://www.epa.gov/greenvehicles/greenhouse-gas-emissions-typical-passenger-vehicle:
- The average passenger vehicle emits about ~250 grams of CO2 per km

If we represent our time ticks as minutes and assume our cars travel at a rate of 50km/h that means that each time ticks a car spends in the environment, it would output 208 g (= 50km * 250g / 60 time ticks) 

Note: these assumptions are pretty arbitrary. For the sake of simplicity we won't take into account travelling vs waiting at a light and decrease in overall average speed that would occur from having many cars in the environment.

I will convert the travel times to use this metrics

**Comment by ZaneLittle** [comment]
The above was added in 94775a3d557b259e679c1b21049b82dd6a380752
